const lessons = [
  {type:'discover',title:'知道两条直角边，斜边有多长？',intro:'先认直角和斜边，再用面积方块发现勾股定理。',time:'⏱ 12 分钟',lab:'直角三角形与面积方块',labels:['直角边 a','直角边 b'],concept:'先认直角，再找斜边',text:'小方框标记的是直角。直角对面的最长边叫斜边 c。',formula:['a²','+','b²','=','c²'],mistake:'易错点：公式只适用于直角三角形；c 永远是直角对面的最长边。',quiz:['梯脚离墙 6 m，梯顶高 8 m，梯子长多少米？',['10 m','12 m','14 m'],'10 m','6² + 8² = 10²，所以梯子长 10 m。']},
  {type:'proof',title:'为什么两个小方块等于一个大方块？',intro:'用四个完全相同的直角三角形拼成大正方形，从面积关系推出公式。',time:'⏱ 14 分钟',lab:'面积拼图证明',labels:['直角边 a','直角边 b'],concept:'同一个大正方形，可以有两种面积算法',text:'大正方形面积是 (a + b)²；也可以看成 4 个三角形面积加中间紫色正方形 c²。',formula:['(a + b)²','=','4 × ab／2','+','c²'],mistake:'易错点：这是面积证明，不是把边长 a 和 b 直接相加。',quiz:['a = 5，b = 12 时，c² 等于多少？',['13','25','169'],'169','5² + 12² = 169，因此 c = 13。']},
  {type:'triples',title:'哪些数字天生是一组“直角边”？',intro:'换几组整数边长，找到不用开方也能得到整数斜边的勾股数。',time:'⏱ 10 分钟',lab:'勾股数发现器',labels:['直角边 a','直角边 b'],concept:'能让 c 也是整数的一组数，叫勾股数',text:'3、4、5 是最常见的一组。5、12、13 和 8、15、17 也满足 a² + b² = c²。',formula:['a²','+','b²','=','c²'],mistake:'易错点：不是所有整数 a、b 都会得到整数 c；但公式对任何直角三角形成立。',quiz:['哪一组是勾股数？',['4、5、6','5、12、13','6、8、9'],'5、12、13','5² + 12² = 13²，这是一组勾股数。']},
  {type:'ladder',title:'梯子够不够长？用模型先算再判断',intro:'把离墙距离和到达高度当作两条直角边，立刻算出梯子至少多长。',time:'⏱ 12 分钟',lab:'梯子长度挑战',labels:['离墙距离','到达高度'],concept:'生活题先画成直角三角形',text:'墙面与地面相交成直角；梯子是斜边 c。先找 a、b，再计算 c = √(a² + b²)。',formula:['c','=','√','(a² + b²)'],mistake:'易错点：梯子长度是斜边，不是把高度和距离直接相加。',quiz:['离墙 5 m，到达高度 12 m，梯子至少多长？',['13 m','15 m','17 m'],'13 m','5² + 12² = 13²，所以至少需要 13 m。']}
];
const baseUpdate = update;
const navItems = [...document.querySelectorAll('.nav-item')];
const titleNode = document.querySelector('.heading h1'), introNode = document.querySelector('.intro'), timeNode = document.querySelector('.time'), labNode = document.querySelector('.lab-head b');
const controlLabels = [...document.querySelectorAll('.control label')], readLabels = [...document.querySelectorAll('.reading span')], resultLabels = [...document.querySelectorAll('.result span')];
const conceptTitle = document.querySelector('.explain h2'), conceptText = document.querySelector('.explain > p:not(.eyebrow)'), formulaBox = document.querySelector('.formula'), mistakeBox = document.querySelector('.mistake'), quizTitle = document.querySelector('.quiz h2'), quizText = document.querySelector('.quiz > p:not(.eyebrow)'), answers = document.querySelector('.answers'), guide = document.getElementById('guide');
let currentLesson=0, stage=1, triple=0;
const tripleSets=[[3,4],[5,12],[8,15],[7,24]];

const stepButton=document.createElement('button');stepButton.className='step-button';stepButton.type='button';document.getElementById('proof').before(stepButton);
function poly(p,fill,stroke){ctx.beginPath();ctx.moveTo(...p[0]);p.slice(1).forEach(q=>ctx.lineTo(...q));ctx.closePath();ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke();}
function labText(s,x,y,color='#33415a',size=13){ctx.fillStyle=color;ctx.font=`600 ${size}px -apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif`;ctx.fillText(s,x,y);}
function tri(A,B,C){ctx.beginPath();ctx.moveTo(...A);ctx.lineTo(...B);ctx.lineTo(...C);ctx.closePath();ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle='#263e60';ctx.lineWidth=3;ctx.stroke();}
function canvasBase(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#fbfdff';ctx.fillRect(0,0,canvas.width,canvas.height);}
function drawTriangle(showSquares){const A=[origin.x,origin.y],B=[origin.x+a*unit,origin.y],C=[origin.x,origin.y-b*unit],c=Math.hypot(a,b);if(showSquares>=2){poly([[A[0],A[1]],[B[0],B[1]],[B[0],B[1]-a*unit],[A[0],A[1]-a*unit]],'#dff1ff','#60a8e9');poly([[A[0],A[1]],[A[0],C[1]],[A[0]-b*unit,C[1]],[A[0]-b*unit,A[1]]],'#fff0df','#f29a54');}if(showSquares>=3){const dx=C[0]-B[0],dy=C[1]-B[1],len=Math.hypot(dx,dy),nx=dy/len*c*unit,ny=-dx/len*c*unit;poly([[B[0],B[1]],[C[0],C[1]],[C[0]+nx,C[1]+ny],[B[0]+nx,B[1]+ny]],'#eee9ff','#876fe0');}tri(A,B,C);ctx.strokeStyle='#263e60';ctx.lineWidth=2;ctx.strokeRect(A[0],A[1]-15,15,15);ctx.fillStyle='#263e60';point(...A);ctx.fillStyle='#007aff';point(...B);ctx.fillStyle='#ff7a35';point(...C);labText('a = '+a,(A[0]+B[0])/2,A[1]+25,'#1671ba');labText('b = '+b,A[0]-42,(A[1]+C[1])/2,'#c66b25');labText('c = '+c.toFixed(2),(B[0]+C[0])/2+11,(B[1]+C[1])/2-9,'#6446ac');return{A,B,C,c};}
function drawDiscover(){canvasBase();const v=drawTriangle(stage);if(stage===1){labText('第 1 步：先找直角',origin.x+25,origin.y+55,'#007aff',14);labText('直角对面最长的一边是斜边 c',origin.x+24,origin.y-b*unit-20,'#6446ac',14);}if(stage===2){labText('蓝色面积 a² = '+a*a,origin.x+8,origin.y-a*unit/2,'#1671ba');labText('橙色面积 b² = '+b*b,origin.x-b*unit+7,origin.y-b*unit/2,'#c66b25');}if(stage===3)labText('紫色面积 c² = '+(a*a+b*b),v.B[0]+15,v.C[1]-22,'#6446ac');}
function drawProof(){canvasBase();const sc=Math.min(14,260/(a+b)),S=(a+b)*sc,x=150,y=47;ctx.strokeStyle='#263e60';ctx.lineWidth=3;ctx.strokeRect(x,y,S,S);if(stage>=2){const P=[[x+a*sc,y],[x+S,y+a*sc],[x+b*sc,y+S],[x,y+b*sc]];poly(P,'#eee9ff','#876fe0');poly([[x,y],P[0],P[3]],'#dff1ff','#60a8e9');poly([P[0],[x+S,y],P[1]],'#fff0df','#f29a54');poly([P[1],[x+S,y+S],P[2]],'#dff1ff','#60a8e9');poly([P[2],[x,y+S],P[3]],'#fff0df','#f29a54');labText('中间紫色正方形面积 = c²',x+S/2-72,y+S/2,'#6446ac',14);}if(stage===1)labText('先看：边长为 a + b 的大正方形',x+30,y+S/2,'#007aff',14);if(stage===3){labText('(a + b)² = 4 × ab／2 + c²',x+58,y+S+55,'#263e60',15);labText('整理后：a² + b² = c²',x+90,y+S+80,'#6446ac',16);}}
function drawTriples(){canvasBase();const v=drawTriangle(1),integer=Number.isInteger(v.c);labText(integer?'这是一组勾股数！':'c 不是整数，但公式仍成立',130,55,integer?'#148164':'#a65b46',16);labText(`${a}² + ${b}² = ${a*a+b*b} = ${v.c.toFixed(2)}²`,130,82,'#53627a',14);}
function drawLadder(){canvasBase();const x=150,y=292,dx=a*unit,dy=b*unit,c=Math.hypot(a,b);ctx.strokeStyle='#82909f';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(x,38);ctx.lineTo(x,y);ctx.lineTo(490,y);ctx.stroke();ctx.strokeStyle='#ff7a35';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(x+dx,y);ctx.lineTo(x,y-dy);ctx.stroke();ctx.strokeStyle='#263e60';ctx.lineWidth=2;ctx.strokeRect(x,y-16,16,16);labText('离墙 '+a+' m',x+dx/2,y+30,'#1671ba');labText('高度 '+b+' m',x-115,y-dy/2,'#c66b25');labText('梯子 c = '+c.toFixed(2)+' m',x+dx/2-7,y-dy/2-12,'#6446ac',15);if(stage===2)labText(`c = √(${a}² + ${b}²) = ${c.toFixed(2)} m`,176,55,'#263e60',16);}
draw=function(){const t=lessons[currentLesson].type;if(t==='discover')drawDiscover();if(t==='proof')drawProof();if(t==='triples')drawTriples();if(t==='ladder')drawLadder();};
function updateGuide(){const t=lessons[currentLesson].type;if(t==='discover')guide.innerHTML='<strong>一步一步来</strong><span class="step-line now">'+['第 1 步：找直角和斜边 c。','第 2 步：看两个小方块的面积。','第 3 步：看紫色大方块，得到公式。'][stage-1]+'</span>';if(t==='proof')guide.innerHTML='<strong>面积证明</strong><span class="step-line now">'+['先看大正方形。','把四个三角形放进去。','比较两种面积，得到公式。'][stage-1]+'</span>';if(t==='triples')guide.innerHTML='<strong>换一组数试试</strong><span class="step-line now">点击“下一组勾股数”，观察斜边什么时候也是整数。</span>';if(t==='ladder')guide.innerHTML='<strong>生活题三步</strong><span class="step-line now">找直角 → 标两条直角边 → 计算斜边 c。</span>';}
function setQuiz(l){quizTitle.textContent='30 秒检验';quizText.textContent=l.quiz[0];answers.innerHTML=l.quiz[1].map(x=>`<button class="answer" data-answer="${x}">${x}</button>`).join('');document.getElementById('feedback').className='feedback';document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const ok=b.dataset.answer===l.quiz[2];document.querySelectorAll('[data-answer]').forEach(x=>x.className='answer');b.className='answer '+(ok?'correct':'incorrect');const f=document.getElementById('feedback');f.textContent=ok?'答对了：'+l.quiz[3]:'再画一个直角三角形，把两条直角边平方相加。';f.className='feedback show '+(ok?'good':'bad')});}
function renderLesson(){const l=lessons[currentLesson],c=Math.hypot(a,b);titleNode.textContent=l.title;introNode.textContent=l.intro;timeNode.textContent=l.time;labNode.textContent='· '+l.lab;navItems.forEach((x,i)=>x.classList.toggle('active',i===currentLesson));controlLabels[0].childNodes[0].textContent=l.labels[0]+' ';controlLabels[1].childNodes[0].textContent=l.labels[1]+' ';readLabels[0].textContent=l.labels[0];readLabels[1].textContent=l.labels[1];readLabels[2].textContent=currentLesson===3?'所需梯长 c':'斜边 c';conceptTitle.textContent=l.concept;conceptText.textContent=l.text;formulaBox.innerHTML=l.formula.map(x=>['+','−','×','／','=','√'].includes(x)?`<i>${x}</i>`:`<span>${x}</span>`).join('');mistakeBox.textContent=l.mistake;resultLabels[0].textContent=currentLesson===3?'距离² a²':'a²';resultLabels[1].textContent=currentLesson===3?'高度² b²':'b²';resultLabels[2].textContent=currentLesson===1?'中间面积 c²':'c²';document.getElementById('aArea').textContent=a*a;document.getElementById('bArea').textContent=b*b;document.getElementById('cArea').textContent=a*a+b*b;document.getElementById('resultNote').textContent=currentLesson===3?`梯子长度 c = √(${a*a} + ${b*b}) = ${c.toFixed(2)} m。`:`${a*a} + ${b*b} = ${a*a+b*b}，因此 ${a}² + ${b}² = ${c.toFixed(2)}²。`;stepButton.textContent=l.type==='triples'?'下一组勾股数 ›':stage===3?'↺ 从第 1 步再看':stage===1?'下一步 ›':'得出结论 ›';updateGuide();setQuiz(l);}
update=function(){baseUpdate();renderLesson();};
function selectLesson(i){currentLesson=i;stage=1;if(i===1){a=3;b=4;}if(i===2)[a,b]=tripleSets[triple];if(i===3){a=6;b=8;}update();}
navItems.forEach((item,i)=>{item.style.cursor='pointer';item.tabIndex=0;item.onclick=()=>selectLesson(i);item.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')selectLesson(i);};});
stepButton.onclick=()=>{if(lessons[currentLesson].type==='triples'){triple=(triple+1)%tripleSets.length;[a,b]=tripleSets[triple];}else stage=stage===3?1:stage+1;update();};
document.getElementById('proof').onclick=()=>{stage=3;update();};document.getElementById('reset').addEventListener('click',()=>selectLesson(currentLesson));selectLesson(0);
